"""add topic_clusters and article_bias tables

Revision ID: 7cf38f6a33f3
Revises: d376777ac017
Create Date: 2026-05-19 15:31:39.777240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf38f6a33f3'
down_revision: Union[str, Sequence[str], None] = 'd376777ac017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False, comment='分析日期'),
    sa.Column('cluster_label', sa.String(length=200), nullable=False, comment='LLM 產生的主題名稱'),
    sa.Column('side_a', sa.String(length=200), nullable=True, comment='立場A描述'),
    sa.Column('side_b', sa.String(length=200), nullable=True, comment='立場B描述'),
    sa.Column('article_count', sa.Integer(), nullable=True, comment='cluster 文章數'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_run_date', 'topic_clusters', ['run_date'], unique=False)
    op.create_table('article_bias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False, comment='neutral | side_a | side_b'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='LLM 判斷理由'),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['topic_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'article_id', name='uq_bias_cluster_article')
    )
    op.create_index('idx_bias_cluster_id', 'article_bias', ['cluster_id'], unique=False)
    op.alter_column('news_articles', 'publish_date',
               existing_type=sa.DATE(),
               comment='發布日期',
               existing_comment='發布日期 (YYYY/MM/DD)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_articles', 'publish_date',
               existing_type=sa.DATE(),
               comment='發布日期 (YYYY/MM/DD)',
               existing_comment='發布日期',
               existing_nullable=False)
    op.drop_index('idx_bias_cluster_id', table_name='article_bias')
    op.drop_table('article_bias')
    op.drop_index('idx_cluster_run_date', table_name='topic_clusters')
    op.drop_table('topic_clusters')
    # ### end Alembic commands ###
