"""Initial migration

Revision ID: 8ea356642b6e
Revises: 
Create Date: 2026-01-07 16:48:05.578339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8ea356642b6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='新聞標題'),
    sa.Column('reporter', sa.String(length=100), nullable=True, comment='記者'),
    sa.Column('summary', sa.Text(), nullable=True, comment='新聞大綱'),
    sa.Column('content', sa.Text(), nullable=True, comment='完整內容（選填）'),
    sa.Column('publish_date', sa.String(length=20), nullable=False, comment='發布日期 (YYYY/MM/DD)'),
    sa.Column('source_url', sa.String(length=1000), nullable=False, comment='新聞連結'),
    sa.Column('source_site', sa.String(length=50), nullable=True, comment='來源網站（如：TVBS、三立、中時）'),
    sa.Column('title_embedding', Vector(1536), nullable=True, comment='標題向量'),
    sa.Column('summary_embedding', Vector(1536), nullable=True, comment='大綱向量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_publish_date', 'news_articles', ['publish_date'], unique=False)
    op.create_index('idx_source_site', 'news_articles', ['source_site'], unique=False)
    op.create_index('idx_summary_embedding_hnsw', 'news_articles', ['summary_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'summary_embedding': 'vector_cosine_ops'})
    op.create_index('idx_title', 'news_articles', ['title'], unique=False)
    op.create_index('idx_title_embedding_hnsw', 'news_articles', ['title_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'title_embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_title_embedding_hnsw', table_name='news_articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'title_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_title', table_name='news_articles')
    op.drop_index('idx_summary_embedding_hnsw', table_name='news_articles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'summary_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_source_site', table_name='news_articles')
    op.drop_index('idx_publish_date', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
