"""remove_content_column

Revision ID: ff6502bff2e5
Revises: 8ea356642b6e
Create Date: 2026-01-09 10:52:57.907270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6502bff2e5'
down_revision: Union[str, Sequence[str], None] = '8ea356642b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='完整內容（選填）'))
    # ### end Alembic commands ###
